[book]
authors = ["tsugumi-sys"]
language = "en"
multilingual = false
src = "src"
title = "my read books"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "navy"
